In [2]:
import torch
import numpy as np

## view (change size of tensor)

In [3]:
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)

In [4]:
print(ft.shape)

torch.Size([2, 2, 3])


In [5]:
print(ft.view([-1, 3])) # ft라는 텐서를 (?, 3)의 크기로 변경 -> (4,3) # think 12 is conserve
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [7]:
print(ft.view([-1, 1, 3])) -> (4,1,3)
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## squeeze (remove the dim is 1), imsqieeze (add the dim 1)

In [8]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [9]:
print(ft.squeeze())  # change (3 * 1) to (1 * 3) (3,)
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [10]:
ft = torch.Tensor([0, 1, 2])
print(ft.shape)

torch.Size([3])


In [11]:
print(ft.unsqueeze(0)) # 인덱스가 0부터 시작하므로 0은 첫번째 차원을 의미한다. # make (1 * x)
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [12]:
print(ft.view(1, -1)) # also make same by view, fix (1 * x)
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [13]:
print(ft.unsqueeze(1)) # make (x * 1)
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [14]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Type Casting

In [15]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [16]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [17]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [18]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## Concatenate

In [19]:
x = torch.FloatTensor([[1, 2], [3, 4]])
y = torch.FloatTensor([[5, 6], [7, 8]])

In [20]:
print(torch.cat([x, y], dim=0))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])


In [21]:
print(torch.cat([x, y], dim=1))

tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


## Stacking(another method concat)

In [22]:
x = torch.FloatTensor([1, 4])
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [23]:
print(torch.stack([x, y, z])) # increase first dimension

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [24]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0)) # infact stack is same with this.

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [26]:
print(torch.stack([x, y, z], dim=1)) # increase second dimension

tensor([[1., 2., 3.],
        [4., 5., 6.]])


## ones_like, zero_like

In [27]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [28]:
print(torch.ones_like(x)) 
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-place Operation(덮어쓰기 연산)

In [29]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [30]:
print(x.mul(2.)) # 곱하기 2를 수행한 결과를 출력
print(x) # 기존의 값 출력

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
